[providers]
node = true

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["cd project/aitoearn-backend && pnpm install"]

[phases.build]
cmds = ["cd project/aitoearn-backend && pnpm nx build aitoearn-server"]

[start]
cmd = "cd project/aitoearn-backend && node dist/apps/aitoearn-server/main.js"
