/**
 * Academy - 小店引流学院页面
 * 包含多个小店运营、抖音/小红书安全绑定的保姆级图文教程
 */
'use client'

import { useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { 
  BookOpen, 
  ShieldCheck, 
  Link as LinkIcon, 
  Layers, 
  ChevronRight, 
  X, 
  CheckCircle, 
  Zap, 
  Crown 
} from 'lucide-react'
import { useGetClientLng } from '@/hooks/useSystem'

interface ArticleItem {
  id: string
  title: string
  desc: string
  category: string
  icon: React.ElementType
  color: string
  content: string[]
}

export default function AcademyPage() {
  const params = useParams()
  const router = useRouter()
  const lng = useGetClientLng()

  // State for article popup
  const [selectedArticle, setSelectedArticle] = useState<ArticleItem | null>(null)

  // Mock articles for tutorials
  const articles: ArticleItem[] = [
    {
      id: 'draft-safety',
      title: lng === 'zh-CN' ? '什么是「静默草稿推送」安全机制？' : 'What is "Silent Draft Push" Safety?',
      desc: lng === 'zh-CN' 
        ? '深入解析为什么我们的系统比任何群发软件都安全。100%模拟自然人，保障同城流量不被警告。' 
        : 'Deep dive into why our draft push is 100% risk-free and avoids platform bans.',
      category: lng === 'zh-CN' ? '安全风控' : 'Security Guide',
      icon: ShieldCheck,
      color: 'bg-emerald-500/10 border-emerald-500/25 text-emerald-600 dark:text-emerald-400',
      content: lng === 'zh-CN' ? [
        '什么是草稿箱推送？—— 我们的系统不会代替您点击“最终发布”。相反，AI 在后台排版好海报和视频后，会通过各大社媒官方合规接口，将其静默“写入”您手机客户端的草稿箱中。',
        '为什么这是100%安全的？ —— 传统群发软件会直接代理发布，很容易被平台（特别是抖音、小红书）的防脚本机制封号。而我们的草稿箱模式下，最终的“发布”动作依然是您自己在手机抖音/小红书上点击的，完全是真实人工行为，对平台来说没有任何特征差异！',
        '这会影响流量吗？ —— 完全不会！因为是人工在真机上发布，享有平台完整的自然流量扶持，100%避免账号权重被限流或限流处罚。'
      ] : [
        'How it works: Instead of directly publishing on your behalf, our AI drafts posters and videos, and securely "saves" them in your phone app\'s drafts folder via official APIs.',
        'Why it is 100% safe: Traditional mass-publishing scripts trigger automatic security bots. Our method leaves the final "publish" tap to your actual hand on your own phone, which is a genuine organic action.',
        'Will this hurt organic traffic? Absolutely not! Since it originates organically from your physical device, it receives full platform feed priority with zero shadowban risk.'
      ]
    },
    {
      id: 'douyin-binding',
      title: lng === 'zh-CN' ? '如何绑定并授权您的同城抖音号？' : 'How to Securely Bind Your Douyin Channel?',
      desc: lng === 'zh-CN' 
        ? '一分钟保姆级指引。无需交出账号密码，通过扫码即可安全连接，支持极速静默草稿箱传输。' 
        : '1-minute step-by-step scanning connection guide without giving out passwords.',
      category: lng === 'zh-CN' ? '账号绑定' : 'Channel Link',
      icon: LinkIcon,
      color: 'bg-indigo-500/10 border-indigo-500/25 text-indigo-600 dark:text-indigo-400',
      content: lng === 'zh-CN' ? [
        '步骤 1：打开「爱易客」工作台的【账号绑定】页面。',
        '步骤 2：点击“绑定抖音号”，系统会弹出一个由抖音官方开放平台生成的安全授权二维码（100%官方可信）。',
        '步骤 3：使用手机打开抖音 APP，点击右上角扫一扫，扫描该二维码，确认登录和授权即可！整个过程系统拿不到您的任何密码，安全极高。',
        '步骤 4：确认授权后，返回爱易客，看到状态更新为“已连接”，您就可以开始在 AI 创意工坊中创作短视频并一键推送到您的抖音草稿箱中啦！'
      ] : [
        'Step 1: Open the "Link Accounts" page in the top sidebar of your aiyike dashboard.',
        'Step 2: Click on "Link Douyin". A secure QR code directly generated by official open platform APIs will be presented.',
        'Step 3: Open the Douyin App on your phone, scan this QR code, and approve the basic draft permission. No passwords are ever accessed.',
        'Step 4: Once completed, the status changes to "Connected". You can now start creating and pushing video drafts instantly!'
      ]
    },
    {
      id: 'xhs-cookie',
      title: lng === 'zh-CN' ? '如何高效绑定您的小红书同城号？' : 'How to Bind Your Xiaohongshu (RedBook) Account?',
      desc: lng === 'zh-CN' 
        ? '小红书免验证授权技巧。通过爱易客浏览器辅助插件，一键自动获取连接，极速进入创作。' 
        : 'Xiaohongshu secure integration using our helper plugin to automatically fetch credentials.',
      category: lng === 'zh-CN' ? '账号绑定' : 'Channel Link',
      icon: LinkIcon,
      color: 'bg-[#F3A390]/10 border-[#F3A390]/25 text-[#F3A390]',
      content: lng === 'zh-CN' ? [
        '步骤 1：下载并安装我们的「爱易客社媒伴侣」浏览器小助手插件。',
        '步骤 2：在浏览器中打开并登录小红书网页版创作者中心。',
        '步骤 3：点击浏览器插件右上角的“一键同步”按钮，插件会自动安全提取小红书的会话 Session 并在本地加密同步给您的爱易客工作台。',
        '步骤 4：绑定成功后，工作台会立刻激活小红书海报和爆单文案的实时卡片预览和草稿写入通道，让您的排版永远优雅规范！'
      ] : [
        'Step 1: Download and install our friendly browser extension "aiyike Social Media Companion".',
        'Step 2: Log in to the official Xiaohongshu Creator Center web dashboard on your desktop.',
        'Step 3: Click "Sync Credentials" inside our extension toolbar. It safely encrypts and synchronizes your session local keys.',
        'Step 4: Verification completes immediately! You can now generate RedBook style cards and enjoy automated drafts.'
      ]
    },
    {
      id: 'multipublish',
      title: lng === 'zh-CN' ? '多平台群发与定时同步指南' : 'Multi-Platform Publishing & Scheduling Guides',
      desc: lng === 'zh-CN' 
        ? '小店主如何全盘托管日常宣发？教您如何使用爱易客排期表，实现一周宣发任务半小时做完。' 
        : 'How to automate a week worth of marketing campaign schedules in just 30 minutes.',
      category: lng === 'zh-CN' ? '高级运营' : 'Advanced Operations',
      icon: Layers,
      color: 'bg-amber-500/10 border-amber-500/25 text-amber-600 dark:text-amber-400',
      content: lng === 'zh-CN' ? [
        '制定爆单日历：建议每周一早上，抽出半小时时间，使用 AI 创作工坊批量制作本周的 5 篇文案和 2 条短视频。',
        '设定智能推送排期：在生成草稿后，点击“选择推送时间”，将其分别设置为周一至周日的晚餐高峰期前（例如下午 4:30）。',
        '手机客户端最终确认：届时系统会自动推送。您只需在每天下班前打开手机，在草稿箱内确认发布即可，工作量减少 90%！',
        '平台差异化调性：写海报时选择小红书模板（粉嫩感），发视频时选择抖音同城模板（配乐欢快），分流推广，效果翻倍。'
      ] : [
        'Create a campaign calendar: Spend 30 minutes every Monday morning to batch-generate 5 copywriting texts and 2 vlogs for the entire week.',
        'Set smart triggers: Click on "Schedule Push" to allocate specific release times (e.g. 4:30 PM just before the dinner rush hour).',
        'Confirm on phone: All materials will arrive in your phone\'s drafts folder automatically. You only spend 10 seconds tapping publish.',
        'Channel differentiation: Use Xiaohongshu templates for elegant visual posters, and Douyin templates for trending music videos.'
      ]
    }
  ]

  return (
    <div className="min-h-screen bg-[#FAF7F2] dark:bg-[#18221B] selection:bg-[#5F7A61]/20 p-6 md:p-16 flex flex-col items-center relative overflow-hidden font-sans">
      
      {/* Background spotlights */}
      <div className="absolute inset-0 pointer-events-none z-0 overflow-hidden">
        <div className="absolute top-[-10%] left-[-10%] w-[600px] h-[600px] rounded-full bg-[radial-gradient(circle,#5F7A61_0%,transparent_70%)] opacity-[0.05] dark:opacity-[0.08] blur-3xl animate-pulse" style={{ animationDuration: '8s' }} />
        <div className="absolute bottom-[-10%] right-[-10%] w-[700px] h-[700px] rounded-full bg-[radial-gradient(circle,#F3A390_0%,transparent_70%)] opacity-[0.05] dark:opacity-[0.08] blur-3xl animate-pulse" style={{ animationDuration: '12s' }} />
      </div>

      <div className="max-w-4xl w-full relative z-10 space-y-12">
        
        {/* Title Block */}
        <div className="text-center space-y-3">
          <div className="mb-4 flex items-center gap-2 rounded-full border border-[#5F7A61]/30 bg-[#5F7A61]/10 px-4 py-1.5 shadow-[0_2px_8px_rgba(95,122,97,0.08)] w-max mx-auto">
            <BookOpen className="size-4 text-[#5F7A61]" />
            <span className="text-[10px] sm:text-xs uppercase tracking-[0.1em] text-[#5F7A61] font-bold">
              {lng === 'zh-CN' ? '保姆级引流手册 · 零门槛获客教学' : 'SHOP OPERATIONS GUIDE & NANNY-LEVEL TUTORIALS'}
            </span>
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold text-[#2A2A2A] dark:text-[#FDFBF7] tracking-tight">
            {lng === 'zh-CN' ? '爱易客 小店引流获客学院' : 'aiyike Local Merchant Academy'}
          </h1>
          <p className="text-[#2A2A2A]/70 dark:text-[#FDFBF7]/70 text-xs sm:text-sm max-w-xl mx-auto font-normal">
            {lng === 'zh-CN'
              ? '专门面向实体商户老板的引流宝典！一分钟看懂静默草稿推送、扫码绑定等硬核风控原理，彻底消除您的技术疑虑。'
              : 'Dedicated training hub for local business owners. Master social media bindings, mass publishing, and safe drafts in 1 minute.'}
          </p>
        </div>

        {/* Notion-Style Guide Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {articles.map((art) => {
            const Icon = art.icon
            
            return (
              <div 
                key={art.id}
                onClick={() => setSelectedArticle(art)}
                className="bg-white/70 dark:bg-[#202C24]/70 backdrop-blur-xl border border-[#5F7A61]/15 p-6 rounded-3xl shadow-[0_4px_24px_rgba(0,0,0,0.01)] hover:shadow-md hover:border-[#5F7A61]/35 hover:-translate-y-0.5 transition-all duration-300 flex flex-col justify-between cursor-pointer group relative active:scale-99 select-none"
              >
                <div>
                  <div className="flex justify-between items-center mb-4">
                    <span className="text-[9px] font-extrabold text-[#5F7A61] dark:text-[#7FA382] tracking-widest uppercase bg-[#5F7A61]/10 px-2 py-0.5 rounded-full">
                      {art.category}
                    </span>
                    <ChevronRight className="size-4 text-[#2A2A2A]/30 group-hover:translate-x-1 transition-transform" />
                  </div>

                  <div className="flex items-start gap-4">
                    {/* Icon Container */}
                    <div className={`size-11 rounded-2xl flex items-center justify-center shrink-0 border ${art.color} group-hover:scale-110 transition-transform`}>
                      <Icon className="size-5.5" />
                    </div>
                    <div className="space-y-2">
                      <h3 className="text-base font-extrabold text-[#2A2A2A] dark:text-[#FDFBF7] leading-snug group-hover:text-[#5F7A61] dark:group-hover:text-[#7FA382] transition-colors">
                        {art.title}
                      </h3>
                      <p className="text-xs text-[#2A2A2A]/60 dark:text-[#FDFBF7]/60 leading-relaxed font-normal">
                        {art.desc}
                      </p>
                    </div>
                  </div>
                </div>

                <div className="mt-6 pt-4 border-t border-[#5F7A61]/10 text-[10px] font-bold text-[#5F7A61] flex items-center gap-1">
                  <span>{lng === 'zh-CN' ? '查看保姆图文教程 →' : 'Read Full Guide →'}</span>
                </div>
              </div>
            )
          })}
        </div>

        {/* Dynamic visual tech bottom quote */}
        <div className="bg-[#FAF7F2]/50 dark:bg-black/10 border border-[#5F7A61]/10 p-6 rounded-3xl text-center max-w-xl mx-auto space-y-2">
          <p className="text-xs text-[#2A2A2A]/70 dark:text-[#FDFBF7]/70 font-semibold flex items-center justify-center gap-1.5">
            <ShieldCheck className="size-4 text-emerald-500" />
            {lng === 'zh-CN' ? '爱易客·国内社媒安全草稿推送保障' : 'aiyike Secure Publishing Guarantee'}
          </p>
          <p className="text-[10px] text-[#2A2A2A]/50 dark:text-[#FDFBF7]/50 leading-relaxed font-normal">
            {lng === 'zh-CN'
              ? '我们的安全协议遵循抖音、小红书官方合规第三方SDK开发白皮书，零密码获取，数据完全在您的本地浏览器沙盒和真机草稿箱流通，100%抵御风控。'
              : 'Our secure sandbox logic complies fully with platform third-party SDK guidelines, with zero password storage and 100% device authorization safety.'}
          </p>
        </div>
      </div>

      {/* Article Detail Popover (Modal) */}
      {selectedArticle && (
        <div className="fixed inset-0 z-50 flex items-center justify-center px-4 py-8 animate-in fade-in duration-200">
          {/* Overlay backdrop */}
          <div 
            onClick={() => setSelectedArticle(null)}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm cursor-pointer" 
          />

          {/* Modal Container */}
          <div className="bg-white dark:bg-[#1C261F] border border-[#5F7A61]/35 rounded-3xl p-6 md:p-8 max-w-lg w-full max-h-[85vh] overflow-y-auto shadow-[0_20px_50px_rgba(0,0,0,0.15)] relative z-10 flex flex-col space-y-6 animate-in zoom-in-95 duration-200 font-sans text-left">
            <button 
              onClick={() => setSelectedArticle(null)}
              className="absolute top-4 right-4 text-[#2A2A2A]/50 dark:text-[#FDFBF7]/50 hover:text-red-500 transition-colors border-none bg-transparent cursor-pointer"
            >
              <X className="size-5" />
            </button>

            <div className="space-y-2 border-b border-[#5F7A61]/10 pb-4">
              <span className="text-[9px] font-extrabold text-[#5F7A61] dark:text-[#7FA382] tracking-widest uppercase bg-[#5F7A61]/10 px-2 py-0.5 rounded-full w-max block">
                {selectedArticle.category}
              </span>
              <h2 className="text-xl font-extrabold text-[#2A2A2A] dark:text-[#FDFBF7]">
                {selectedArticle.title}
              </h2>
            </div>

            {/* List of article steps */}
            <div className="space-y-4 flex-1">
              {selectedArticle.content.map((paragraph, index) => (
                <div key={index} className="flex items-start gap-3">
                  <div className="size-5 rounded-full bg-[#5F7A61]/10 text-[#5F7A61] text-[10px] font-extrabold flex items-center justify-center shrink-0 mt-0.5">
                    {index + 1}
                  </div>
                  <p className="text-xs text-[#2A2A2A]/80 dark:text-[#FDFBF7]/80 leading-relaxed font-normal">
                    {paragraph}
                  </p>
                </div>
              ))}
            </div>

            {/* Modal Bottom CTA */}
            <div className="pt-4 border-t border-[#5F7A61]/10 flex justify-end gap-3 select-none">
              <button 
                onClick={() => setSelectedArticle(null)}
                className="px-4 py-2 border border-neutral-300 dark:border-neutral-700 text-[#2A2A2A] dark:text-[#FDFBF7] text-xs font-bold rounded-xl cursor-pointer hover:bg-neutral-50 dark:hover:bg-neutral-900 transition-all"
              >
                {lng === 'zh-CN' ? '关闭' : 'Close'}
              </button>
              <button 
                onClick={() => {
                  setSelectedArticle(null)
                  router.push(`/${params.lng}/ai-social`)
                }}
                className="px-4 py-2 bg-[#5F7A61] text-[#FAF7F2] border-none text-xs font-bold rounded-xl cursor-pointer hover:bg-[#5F7A61]/90 transition-all shadow-sm flex items-center gap-1"
              >
                <Zap className="size-3.5 fill-[#FAF7F2]" />
                {lng === 'zh-CN' ? '立即去创作' : 'Start Creating'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
